export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
export const ADD_COMMENT = "ADD_COMMENT";
export const SET_COMMENT_BODY = "SET_COMMENT_BODY";
export const SET_COMMENT_AUTHOR = "SET_COMMENT_AUTHOR";
export const CLEAR_FORM = "CLEAR_FORM";
